services:
    ubuntu:
        public: true
        container_name: vnc
        image: imlala/ubuntu-xfce-vnc-novnc:latest
        shm_size: "3gb"
        ports:
            - 6080:6080
        environment: 
            - VNC_PASSWD=123456
            - GEOMETRY=1920x1080
            - TZ=Asia/Shanghai
            - DEPTH=24
        volumes: 
            - /root/Desktop
            - /home
        resources:
          cpu: 1000m
          memory: 2048Mi
          storage:
            size: 3Gi
            class: standard
